# Key Vault Access Test Pipeline
trigger: none

parameters:
- name: targetPool
  displayName: 'Target Agent Pool'
  type: string
  default: 'Default'
  values:
  - 'Default'

variables:
- group: KeyVault-Variables

stages:
- stage: WriteSecret
  displayName: 'Write Secret to Key Vault'
  pool:
    name: ${{ parameters.targetPool }}
  jobs:
  - job: WriteToKeyVault
    displayName: 'Store Pipeline Runtime Info'
    steps:
    - task: AzureCLI@2
      displayName: 'Write timestamp to Key Vault (Linux)'
      inputs:
        azureSubscription: 'LabKeyVaultConnection'
        scriptType: bash
        scriptLocation: 'inlineScript'
        inlineScript: |
          timestamp=$(date '+%Y-%m-%d %H:%M:%S')
          agentName="${AGENT_NAME:-unknown}"
          poolName="${AGENT_POOLNAME:-unknown}"
          secretValue="Pipeline run at $timestamp by agent $agentName in pool $poolName"
          
          echo "Writing secret to Key Vault: $(KeyVaultName)"
          echo "Secret value: $secretValue"
          
          # Write the secret
          az keyvault secret set --vault-name "$(KeyVaultName)" --name "PipelineRunInfo" --value "$secretValue"
          
          echo "✅ Secret written successfully"

- stage: ReadSecret
  displayName: 'Read Secret from Key Vault'
  dependsOn: WriteSecret
  pool:
    name: ${{ parameters.targetPool }}
  jobs:
  - job: ReadFromKeyVault
    displayName: 'Retrieve and Verify Secret'
    steps:
    - task: AzureCLI@2
      displayName: 'Read timestamp from Key Vault (Linux)'
      inputs:
        azureSubscription: 'LabKeyVaultConnection'
        scriptType: bash
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Reading secret from Key Vault: $(KeyVaultName)"
          
          # Read the secret
          secretValue=$(az keyvault secret show --vault-name "$(KeyVaultName)" --name "PipelineRunInfo" --query "value" -o tsv)
          
          echo "✅ Secret retrieved successfully:"
          echo "Value: $secretValue"
          
          # Also read the original test secret
          testSecret=$(az keyvault secret show --vault-name "$(KeyVaultName)" --name "TestSecret" --query "value" -o tsv)
          echo "✅ Test secret value: $testSecret"
