parameters:
  - name: action
    type: string
    values:
      - setup
      - break
      - destroy
  - name: labNumber
    type: string
    default: ''

stages:
  - stage: LabStage
    displayName: DNS Lab - ${{ parameters.action }}
    jobs:
      - job: LabJob
        displayName: Run ${{ parameters.action }} for $(Build.RequestedFor)
        pool:
          name: 'ADO-Pipeline-Network-Troubleshooting-Labs-Pool'
        steps:
          - checkout: self

          - script: |
              echo "Build triggered by: $(Build.RequestedFor)"
              echo "Lab action: ${{ parameters.action }}"
            displayName: 'Display Context'

          - script: |
              if [ -z "${{ parameters.labNumber }}" ] && [[ "${{ parameters.action }}" == "break" ]]; then
                echo "##vso[task.logissue type=error]labNumber parameter is required for break action."
                exit 1
              fi
            displayName: 'Validate Parameters'

          - script: |
              curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
              wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
              echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
              sudo apt-get update && sudo apt-get install -y terraform
            displayName: 'Install Azure CLI and Terraform'

          - script: |
              echo "=== DEBUG: Available Variables ==="
              echo "ADO_ORG_URL: $(ADO_ORG_URL)"
              echo "ADO_PROJECT: $(ADO_PROJECT)"
              echo "ADO_POOL: $(ADO_POOL)"
              echo "AZURE_TENANT: $(AZURE_TENANT)"
              echo "Build.RequestedFor: $(Build.RequestedFor)"
              echo "LAB_NUMBER: ${{ parameters.labNumber }}"
              echo "==============================="
            displayName: 'Debug: Check Variables'

          - task: AzureCLI@2
            displayName: 'Run lab action: ${{ parameters.action }}'
            inputs:
              azureSubscription: 'LabConnection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                export REQUESTED_FOR="$(Build.RequestedFor)"
                export LAB_NUMBER="${{ parameters.labNumber }}"
                export ADO_ORG_URL="$(ADO_ORG_URL)"
                export ADO_PAT="$(ADO_PAT)"
                export ADO_PROJECT="$(ADO_PROJECT)"
                export ADO_POOL="$(ADO_POOL)"
                export AZURE_TENANT="$(AZURE_TENANT)"
                
                echo "=== DEBUG: Script Environment ==="
                echo "REQUESTED_FOR=${REQUESTED_FOR}"
                echo "ADO_ORG_URL=${ADO_ORG_URL}"
                echo "ADO_PROJECT=${ADO_PROJECT}"
                echo "ADO_POOL=${ADO_POOL}"
                echo "AZURE_TENANT=${AZURE_TENANT}"
                echo "LAB_NUMBER=${LAB_NUMBER}"
                echo "=================================="
                echo ""
                echo "Running action: ${{ parameters.action }} for user: $REQUESTED_FOR"

                case "${{ parameters.action }}" in
                  setup)
                    chmod +x ./setup.sh
                    ./setup.sh
                    ;;
                  break)
                    chmod +x ./break-lab.sh
                    ./break-lab.sh "$LAB_NUMBER"
                    ;;
                  destroy)
                    chmod +x ./destroy.sh
                    ./destroy.sh
                    ;;
                  *)
                    echo "Unknown action: ${{ parameters.action }}"
                    exit 1
                    ;;
                esac
